version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - softplayer_data:/var/lib/mysql

volumes:
  softplayer_data: