spring:
  datasource:
    url: mysql://b28ec969abbf0a:aeddf601@us-cdbr-east-02.cleardb.com/heroku_f45af10224110ca?reconnect=true
  jpa:
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false