server:
  error:
    include-stacktrace: on_param

spring:
  application:
    name: soft
  datasource:
    url: jdbc:mysql://localhost:3308/softplayer?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: secret
  jpa:
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: update
